/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import pos.Pos;
import server.OperacoesRemote;

/**
 *
 * @author randler
 */
public class MainOperacoes extends javax.swing.JFrame {

    
    private int cont = 0;
    private double chegada;
    OperacoesRemote operacaoM1;
    OperacoesRemote operacaoM2;
    OperacoesRemote operacaoM3;
    OperacoesRemote operacaoM4;

    public double getChegada() {
        return chegada;
    }

    public void setChegada(double chegada) {
        this.chegada = chegada;
    }    
    
    public int getCont() {
        return cont;
    }

    public void setCont(int cont) {
        this.cont = cont;
    }
    
    
    /**
     * Creates new form MainOperacoes
     */
    public MainOperacoes() {
        try {
            this.operacaoM4 = (OperacoesRemote) Naming.lookup("//localhost/Operacoes");
            this.operacaoM3 = (OperacoesRemote) Naming.lookup("//localhost/Operacoes");
            this.operacaoM2 = (OperacoesRemote) Naming.lookup("//localhost/Operacoes");
            this.operacaoM1 = (OperacoesRemote) Naming.lookup("//localhost/Operacoes");
            initComponents();
            
            this.setLocation(500, 400);
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(MainOperacoes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonResultado = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelSaidaResultado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonResultado.setText("Resultado");
        jButtonResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResultadoActionPerformed(evt);
            }
        });

        jLabel1.setText("Insira a operação:");

        jLabel2.setText("Resultado:");

        jLabel3.setFont(new java.awt.Font("Droid Sans", 1, 24)); // NOI18N
        jLabel3.setText("Operações Distribuidas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonResultado))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSaidaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonResultado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSaidaResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResultadoActionPerformed
        
        Pos pos = new Pos();
        
        double res = 0;
        String jtext, op1 = "";
        
        jtext = jTextField1.getText();
        
        jtext = pos.posFixa(jtext);
                // 538*+5+95*-    
        for (int i = 0; i < jtext.length(); i++) {
            if(isNumber(jtext.charAt(i))){
                op1+=jtext.charAt(i);
            }else{
                if(op1.length() == 2){
                    op1+=jtext.charAt(i);
                    cont++;
                    String resultado = enviar(op1);
                    op1 = resultado;
                }else if (op1.length() == 3){
                    String sobra = op1.substring(0, 1);
                    op1 = op1.substring(1);
                    op1+=jtext.charAt(i);
                    cont++;
                    String resultado = enviar(op1);
                    op1 = sobra+""+resultado;
                }
                
            }
            
            
        }
        res = Integer.parseInt(op1);
                      
                jLabelSaidaResultado.setText(""+res);
            
        
        
        
    }//GEN-LAST:event_jButtonResultadoActionPerformed

private String enviar(String op1){
        int chega = 0;
        String saida = "";
    
        try {
            
            switch(getCont()){
                case 1:
                    chega = operacaoM1.verificaOperacao(op1);
                    break;
                case 2:
                    chega = operacaoM2.verificaOperacao(op1);
                    break;
                case 3:
                    chega = operacaoM3.verificaOperacao(op1);
                    break;
                case 4:
                    chega = operacaoM4.verificaOperacao(op1);
                    setCont(0);
                    break;
                    
            }
            
        } catch (RemoteException ex) {
            Logger.getLogger(MainOperacoes.class.getName()).log(Level.SEVERE, null, ex);
        }
        String temp = String.valueOf(chega);
        
        
        if(temp.length()>1){
            saida = temp.substring(1,2);
            if(!isNumber(saida))
               saida = temp.substring(2,3); 
        }else
            saida = temp;
        
        return saida;
    
}    
private boolean isNumber(String var){
    boolean saida= false;
    try{
        String temp = String.valueOf(var);
        Integer.parseInt(temp);
        saida = true;
    }catch(NumberFormatException e){
        saida = false;
    }
    return saida;
    
}

private boolean isNumber(char var){
    boolean saida= false;
    try{
        String temp = String.valueOf(var);
        Integer.parseInt(temp);
        saida = true;
    }catch(NumberFormatException e){
        saida = false;
    }
    return saida;
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelSaidaResultado;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
